import 'package:dio/dio.dart';
import 'package:html/parser.dart' as html_parser;

import '../../../domain/models/chapter.dart';
import '../../../domain/models/manga.dart';
import '../http_manga_source.dart';

// HTML scraper for https://mangafire.to (EN)
//
// Chapter list:  GET /ajax/manga/{hid}/chapter/en
//   Response:    JSON { "result": "<li data-number='...'><a href='/read/...'>" }
// Chapter pages: VRF token generated by obfuscated JS — cannot be called directly.
//   requiresJavaScript = true: chapter taps open Source Browser WebView instead.
//
// chapter.url stores the full reader path: "read/{slug}.{hid}/en/chapter-{number}"
//
// ID format: the manga slug WITHOUT the /manga/ prefix.
//   e.g. "one-piece.lp7ke" (not "/manga/one-piece.lp7ke")
//   getDetails / getChapters prepend /manga/ internally.
class MangaFireSource extends HttpMangaSource {
  @override
  String get id => 'mangafire';

  @override
  bool get requiresJavaScript => true;

  @override
  String get name => 'MangaFire';

  @override
  String get baseUrl => 'https://mangafire.to';

  @override
  String get iconAsset => 'assets/svg/sources/mangafire.svg';

  @override
  Map<String, String> get defaultHeaders => {
    ...super.defaultHeaders,
    'Referer': 'https://mangafire.to/',
  };

  // ── helpers ────────────────────────────────────────────────────────────────

  MangaStatus _toStatus(String? raw) => switch (raw?.toLowerCase().trim()) {
        'releasing' || 'ongoing' => MangaStatus.ongoing,
        'completed' => MangaStatus.completed,
        'on_hiatus' || 'hiatus' => MangaStatus.hiatus,
        'discontinued' || 'cancelled' => MangaStatus.cancelled,
        _ => MangaStatus.unknown,
      };

  // MangaFire may show one card per language for each manga.
  // We deduplicate by href so each manga appears only once.
  List<MangaSummary> _parseCards(String html) {
    final doc = html_parser.parse(html);
    final seen = <String>{};
    final results = <MangaSummary>[];

    for (final card in doc.querySelectorAll('.unit .inner, .unit')) {
      final a = card.querySelector('a.poster') ??
          card.querySelector('a[href*="/manga/"]') ??
          card.querySelector('a');
      final href = a?.attributes['href'] ?? '';
      if (href.isEmpty || !href.contains('/manga/')) continue;
      if (!seen.add(href)) continue; // skip duplicate language variants

      final path = Uri.tryParse(href)?.path ?? href;
      // Store only the slug (after /manga/) — avoids double prefix in router.
      final slug = path.startsWith('/manga/')
          ? path.substring(7).replaceAll(RegExp(r'/$'), '')
          : path.replaceAll(RegExp(r'^/|/$'), '');

      final img = card.querySelector('img');
      final cover = img?.attributes['src'] ??
          img?.attributes['data-src'] ??
          card.querySelector('source')?.attributes['srcset'] ?? '';

      // img[alt] has the real title — .name may contain the language code.
      final title = img?.attributes['alt']?.trim() ??
          a?.attributes['title']?.trim() ??
          card.querySelector('a.name')?.text.trim() ??
          card.querySelector('.info .name')?.text.trim() ??
          card.querySelector('.name')?.text.trim() ??
          card.querySelector('b')?.text.trim() ?? '';

      if (title.isEmpty || slug.isEmpty) continue;
      results.add(MangaSummary(id: slug, sourceId: id, title: title, coverUrl: cover));
    }
    return results;
  }

  // ── MangaSource ────────────────────────────────────────────────────────────

  @override
  Future<List<MangaSummary>> getPopular(int page) => fetchHtml(
        '$baseUrl/filter',
        params: <String, dynamic>{
          'sort': 'trending_7d',
          'language[]': 'en',
          'page': page,
        },
      ).then(_parseCards);

  @override
  Future<List<MangaSummary>> getLatest(int page) => fetchHtml(
        '$baseUrl/filter',
        params: <String, dynamic>{
          'sort': 'recently_updated',
          'language[]': 'en',
          'page': page,
        },
      ).then(_parseCards);

  @override
  Future<List<MangaSummary>> search(String query, int page) => fetchHtml(
        '$baseUrl/filter',
        params: <String, dynamic>{
          'keyword': query,
          'language[]': 'en',
          'page': page,
        },
      ).then(_parseCards);

  @override
  Future<MangaDetails> getDetails(String mangaUrl) async {
    // mangaUrl = slug (e.g. "one-piece.lp7ke") — add /manga/ prefix
    final html = await fetchHtml('$baseUrl/manga/$mangaUrl');
    final doc = html_parser.parse(html);

    final title = doc.querySelector('.manga-name')?.text.trim() ??
        doc.querySelector('h1')?.text.trim() ?? '';
    final cover = doc.querySelector('.manga-poster img')?.attributes['src'] ??
        doc.querySelector('.poster img')?.attributes['src'] ?? '';
    final synopsis = doc.querySelector('.synopsis p')?.text.trim() ??
        doc.querySelector('[class*="description"] p')?.text.trim() ?? '';
    final statusEl = doc.querySelector('.manga-status .label') ??
        doc.querySelector('[class*="status"]');
    final status = _toStatus(statusEl?.text);
    final authors = doc
        .querySelectorAll('.manga-author a, [class*="author"] a')
        .map((e) => e.text.trim())
        .where((s) => s.isNotEmpty)
        .toList();

    return MangaDetails(
      id: mangaUrl,
      title: title,
      coverUrl: cover,
      synopsis: synopsis,
      status: status,
      authors: authors,
    );
  }

  @override
  Future<List<ChapterSummary>> getChapters(String mangaUrl) async {
    // mangaUrl = slug (e.g. "one-piece.lp7ke")
    // AJAX endpoint uses only the identifier AFTER the last dot:
    //   "one-piece.lp7ke" → "lp7ke"
    // (same as Mihon's MangaFire extension: manga.url.substringAfterLast("."))
    final dotIdx = mangaUrl.lastIndexOf('.');
    final mangaId =
        dotIdx >= 0 ? mangaUrl.substring(dotIdx + 1) : mangaUrl;

    final response = await client.get<dynamic>(
      '/ajax/manga/$mangaId/chapter/en',
      options: Options(headers: {
        'X-Requested-With': 'XMLHttpRequest',
        'Accept': 'application/json, */*',
      }),
    );
    final data = response.data;
    final String html;
    if (data is Map<String, dynamic>) {
      html = data['result'] as String? ?? data['html'] as String? ?? '';
    } else {
      html = data as String? ?? '';
    }

    final doc = html_parser.parse(html);
    final chapters = <ChapterSummary>[];

    var items = doc.querySelectorAll('li[data-id]');
    if (items.isEmpty) items = doc.querySelectorAll('li');

    for (final li in items) {
      final a = li.querySelector('a');
      final href = a?.attributes['href'] ?? '';
      // href = "/read/one-piecee.dkw/en/chapter-1186"
      if (href.isEmpty) continue;
      // chapter number from data-number attribute or from href
      final dataNumber = li.attributes['data-number'] ?? '';
      final numMatch = dataNumber.isNotEmpty
          ? RegExp(r'\d+\.?\d*').firstMatch(dataNumber)
          : RegExp(r'chapter-(\d+\.?\d*)').firstMatch(href);
      final number = double.tryParse(numMatch?.group(1) ?? numMatch?.group(0) ?? '') ?? 0.0;
      final rawTitle = a?.querySelector('.name')?.text.trim() ??
          a?.text.trim() ?? '';
      // Use href as chapter URL so Source Browser can open the exact page
      final chapterId = href.replaceFirst(RegExp(r'^/'), '');
      chapters.add(ChapterSummary(
        id: chapterId,
        title: rawTitle.isNotEmpty
            ? rawTitle
            : 'Chapter ${dataNumber.isNotEmpty ? dataNumber : number.toStringAsFixed(0)}',
        number: number,
        url: chapterId,
      ));
    }

    // API returns newest-first — reverse to ascending for DB storage
    return chapters.reversed.toList();
  }

  @override
  String chapterBrowserUrl(String chapterUrl) =>
      chapterUrl.startsWith('http') ? chapterUrl : '$baseUrl/$chapterUrl';

  // VRF token required by MangaFire cannot be generated in Dart.
  // requiresJavaScript = true causes chapter taps to open Source Browser instead.
  @override
  Future<List<String>> getPages(String chapterUrl,
      {bool dataSaver = false}) async => const [];
}
